#!/usr/bin/env node

const greedly = require('./greedly')
    , fs = require('fs')
    , path = require('path')
    , minimist = require('minimist')

const argv = minimist(process.argv.slice(2))
const config = require(path.resolve(argv.i))
if (argv.verbose) config.logger = console.log

const callback = feed => fs.writeFileSync(path.resolve(argv.o), feed.atom)
const instance = new greedly.Manager(config)
  .data(callback)
  .start()

if (argv.t) setTimeout(instance.stop.bind(instance), argv.t)
