#!/usr/bin/env node

const Manager = require('./greedly.js').Manager
    , fs = require('fs')
    , path = require('path')
    , minimist = require('minimist')

let argv = minimist(process.argv.slice(2))

let callback = feed => {
  fs.writeFileSync(path.resolve(argv.o), feed.atom)
}
config = require(path.resolve(argv.i))
if (argv.verbose) {
  config.logger = console.log
}

let instance = new Manager(config)
  .data(callback)
  .start()

if (argv.t) {
  setTimeout(instance.stop.bind(instance), argv.t)
}
