#!/usr/bin/env node

const Manager = require('./greedly.js').Manager
    , fs = require('fs')
    , path = require('path')

let [,, config, output, timeout] = process.argv

let callback = feed => {
  fs.writeFileSync(path.resolve(output), feed.atom)
}
config = require(path.resolve(config))

let instance = new Manager(config)
  .data(callback)
  .start()

if (timeout) {
  setTimeout(process.exit, timeout)
}
